<?php

define("URL_BASE_BACKEND", "");
define("URL_BASE_FRONTEND", "");

//HTTP ERROR CODE CONFIGURATION
define("HTTP_CODE_BAD_REQUEST", 400);
define("HTTP_CODE_UNAUTHORIZED", 401);
define("HTTP_CODE_FORBIDDEN", 403);
define("HTTP_CODE_NOT_FOUND", 404);
define("HTTP_CODE_METHOD_NOT_ALLOWED", 405);


//DATABASE CONFIGURATION
define("DB_DBMS", "");
define("DB_HOSTNAME", "");
define("DB_PORT", 3306);
define("DB_DATABASE", "");
define("DB_USERNAME", "");
define("DB_PASSWORD", "");

